apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calendar-to-mqtt
metadata:
  name: kustomize-calendar-to-mqtt
resources:
- deployment.yaml
- namespace.yaml
configMapGenerator:
  - name: config-configmap
    files:
      - config.yaml=config.yaml
    options:
      disableNameSuffixHash: false