name: docker-build-and-release

permissions:
  packages: write
  contents: write # Required to create release

on:
  push:
    branches:
      - main
    paths:
        - 'Dockerfile'
        - '.dockerignore'
        - '.github/workflows/docker-build-and-release.yml'
        - 'go.mod'
        - 'go.sum'
        - 'internal/**'
        - 'cmd/**'
env:
  REGISTRY_IMAGE: teknikens-hus/calendar-to-mqtt

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.REGISTRY_IMAGE }}:latest
            ghcr.io/${{ env.REGISTRY_IMAGE }}:1.${{ github.run_number }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.${{ github.run_number }}
          name: Release 1.${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}